version: "3.5"

services:
  db:
    image: nichealpham95/his:mssql-db-v1.0
    networks:
      - shared_network
    restart: always
    volumes:
      - mssql_volume:/var/opt/mssql
    environment: 
      - SA_PASSWORD=OpenHis@Sql123#
  
  api:
    image: nichealpham95/his-v2:his-api
    ports:
      - 2001:80
    networks:
      - shared_network
    restart: always
    depends_on: 
      - db
    environment: 
      - HIS_APP_MSSQL_DB_HOST=db
      - HIS_APP_MSSQL_DB_USER=sa
      - HIS_APP_MSSQL_DB_PASSWORD=OpenHis@Sql123#
      - HIS_APP_ACCESS_TOKEN_ENCRYPTION_KEY=sandrasoft@2021#

  hrm:
    image: nichealpham95/his-v2:his-hrm
    ports:
      - 3001:80
    networks:
      - shared_network
    restart: always
    depends_on: 
      - api
    environment: 
      - VUE_APP_API=http://localhost:2001/api

  pas:
    image: nichealpham95/his-v2:his-pas
    ports:
      - 3002:80
    networks:
      - shared_network
    restart: always
    depends_on: 
      - api
    environment: 
      - VUE_APP_API=http://localhost:2001/api

  emr:
    image: nichealpham95/his-v2:his-emr
    ports:
      - 3003:80
    networks:
      - shared_network
    restart: always
    depends_on: 
      - api
    environment: 
      - VUE_APP_API=http://localhost:2001/api

networks:
  shared_network:

volumes:
  mssql_volume:
