version: "3.5"

services:
  db:
    image: nichealpham95/his-v2:his-db
    ports:
      - 1433:1433
    networks:
      - shared_network
    restart: always
    volumes:
      - mssql_volume:/var/opt/mssql
    env_file:
      - ./.env

  api:
    image: nichealpham95/his-v2:his-api
    ports:
      - 2001:80
    networks:
      - shared_network
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env

  ai:
    image: nichealpham95/his-v2:his-ai
    ports:
      - 2002:80
    networks:
      - shared_network
    restart: always
    depends_on:
      - db
      - api
    volumes:
      - ai_volume:/app/public
    env_file:
      - ./.env

  hrm:
    image: nichealpham95/his-v2:his-hrm
    ports:
      - 3001:80
    networks:
      - shared_network
    restart: always
    depends_on:
      - api
    env_file:
      - ./.env

  pas:
    image: nichealpham95/his-v2:his-pas
    ports:
      - 3002:80
    networks:
      - shared_network
    restart: always
    depends_on:
      - api
    env_file:
      - ./.env

  emr:
    image: nichealpham95/his-v2:his-emr
    ports:
      - 3003:80
    networks:
      - shared_network
    restart: always
    depends_on:
      - api
    env_file:
      - ./.env

networks:
  shared_network:

volumes:
  mssql_volume:
  ai_volume:
